//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSBillet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMSBillet.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket Voucher.
        /// </summary>
        public static string uiButtonBuyNewTicketVoucher {
            get {
                return ResourceManager.GetString("uiButtonBuyNewTicketVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Ticket Voucher Remains.
        /// </summary>
        public static string uiButtonCheckTicketVoucherAmount {
            get {
                return ResourceManager.GetString("uiButtonCheckTicketVoucherAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ticket SMS.
        /// </summary>
        public static string uiButtonCreateSMS {
            get {
                return ResourceManager.GetString("uiButtonCreateSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Voucher Usage SMS.
        /// </summary>
        public static string uiButtonCreateTicketVoucherSMS {
            get {
                return ResourceManager.GetString("uiButtonCreateTicketVoucherSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Zones.
        /// </summary>
        public static string uiExtraAdditionalZone {
            get {
                return ResourceManager.GetString("uiExtraAdditionalZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Bicycle.
        /// </summary>
        public static string uiExtraPlusBicycle {
            get {
                return ResourceManager.GetString("uiExtraPlusBicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string uiHeaderExtra {
            get {
                return ResourceManager.GetString("uiHeaderExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Ticket (Copenhagen).
        /// </summary>
        public static string uiHeaderMain {
            get {
                return ResourceManager.GetString("uiHeaderMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Zones.
        /// </summary>
        public static string uiHeaderNumberOfZones {
            get {
                return ResourceManager.GetString("uiHeaderNumberOfZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start (zone/station).
        /// </summary>
        public static string uiHeaderStartingPoint {
            get {
                return ResourceManager.GetString("uiHeaderStartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type.
        /// </summary>
        public static string uiHeaderTicketType {
            get {
                return ResourceManager.GetString("uiHeaderTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you order an adult or child ticket, you can opt for bike ticket..
        /// </summary>
        public static string uiInfoTicketAddBicycleText {
            get {
                return ResourceManager.GetString("uiInfoTicketAddBicycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to buy a single zone ticket in addition to an existing ticket, select Extra, then select 1 zone. If you do not select Extra is 2 zones minimum purchase..
        /// </summary>
        public static string uiInfoTicketAdditionalZoneText {
            get {
                return ResourceManager.GetString("uiInfoTicketAdditionalZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SMS.
        /// </summary>
        public static string uiInfoTicketCreateSMSHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketCreateSMSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to generate the SMS, you need to send to buy an SMS ticket. You must enter a start-zone/stop/station before you can click on this button..
        /// </summary>
        public static string uiInfoTicketCreateSMSText {
            get {
                return ResourceManager.GetString("uiInfoTicketCreateSMSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Zones.
        /// </summary>
        public static string uiInfoTicketNumberOfZonesHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketNumberOfZonesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of zones your trip spans..
        /// </summary>
        public static string uiInfoTicketNumberOfZonesText {
            get {
                return ResourceManager.GetString("uiInfoTicketNumberOfZonesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string uiInfoTicketStartHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketStartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the zone number you start your journey from or enter the station / stop you are at. If using bus stop, enter S before the stop number. For example S253.
        /// </summary>
        public static string uiInfoTicketStartText {
            get {
                return ResourceManager.GetString("uiInfoTicketStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type (Bicycle).
        /// </summary>
        public static string uiInfoTickettypeBicycleHeader {
            get {
                return ResourceManager.GetString("uiInfoTickettypeBicycleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you select the ticket type bike, you buy only one ticket for your bike. One bicycle ticket is valid for up to 7 zones. It&apos;s free to bring bikes in the S-trains.
        /// </summary>
        public static string uiInfoTickettypeBicycleText {
            get {
                return ResourceManager.GetString("uiInfoTickettypeBicycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type (Adult/child).
        /// </summary>
        public static string uiInfoTickettypeHeader {
            get {
                return ResourceManager.GetString("uiInfoTickettypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether the ticket is for an adult (over 14) or child (under 14)..
        /// </summary>
        public static string uiInfoTickettypeText {
            get {
                return ResourceManager.GetString("uiInfoTickettypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Ticket Voucher.
        /// </summary>
        public static string uiInfoTicketVoucherButtonBuyVoucherHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonBuyVoucherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By sending this SMS, you will buy a 20-zone SMS voucher..
        /// </summary>
        public static string uiInfoTicketVoucherButtonBuyVoucherText {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonBuyVoucherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Ticket Voucher Remains.
        /// </summary>
        public static string uiInfoTicketVoucherButtonCheckVoucherHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonCheckVoucherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By sending this SMS, you will get a text back telling you how many unused clips you have left on your SMS voucher..
        /// </summary>
        public static string uiInfoTicketVoucherButtonCheckVoucherText {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonCheckVoucherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Voucher Use SMS.
        /// </summary>
        public static string uiInfoTicketVoucherButtonCreateSMSHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonCreateSMSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to generate the SMS you must send to use clip on your SMS voucher. You must enter a start-zone/stop/station before you can click on this button..
        /// </summary>
        public static string uiInfoTicketVoucherButtonCreateSMSText {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherButtonCreateSMSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type (Adult/child).
        /// </summary>
        public static string uiInfoTicketVoucherTickettypeHeader {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherTickettypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether the ticket is for an adult (over 14) or child (under 14).
        /// </summary>
        public static string uiInfoTicketVoucherTickettypeText {
            get {
                return ResourceManager.GetString("uiInfoTicketVoucherTickettypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string uiTabHeaderInfo {
            get {
                return ResourceManager.GetString("uiTabHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string uiTabHeaderTicket {
            get {
                return ResourceManager.GetString("uiTabHeaderTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Voucher.
        /// </summary>
        public static string uiTabHeaderTicketVoucher {
            get {
                return ResourceManager.GetString("uiTabHeaderTicketVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string uiTickettypeAdult {
            get {
                return ResourceManager.GetString("uiTickettypeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle.
        /// </summary>
        public static string uiTickettypeBicycle {
            get {
                return ResourceManager.GetString("uiTickettypeBicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string uiTickettypeChild {
            get {
                return ResourceManager.GetString("uiTickettypeChild", resourceCulture);
            }
        }
    }
}
